<?php
/**
 * @file
 * Replacement for PHP's get_browser() function.
 */

// Include browscap data import functions
include_once('import.inc');

/**
 * Implementation of hook_perm().
 */
function browscap_perm() {
  return array(
    'administer browscap',
    'view browscap reports',
  );
}

/**
 * Implementation of hook_menu().
 */
function browscap_menu() {
  $items['admin/settings/browscap'] = array(
    'title' => 'Browscap',
    'description' => 'Configure user agent monitoring and browscap information settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('browscap_settings_form'),
    'access arguments' => array('administer browscap'),
    'file' => 'browscap.admin.inc',
  );
  $items['admin/reports/browscap'] = array(
    'title' => 'Browscap',
    'description' => 'Browser-specific site statistics.',
    'page callback' => 'browscap_top_useragents',
    'page arguments' => array('all'),
    'access arguments' => array('view browscap reports'),
    'file' => 'browscap.reports.inc',
    'weight' => 5,
  );
  $items['admin/reports/browscap/useragents'] = array(
    'title' => 'All',
    'access arguments' => array('view browscap reports'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/reports/browscap/browsers'] = array(
    'title' => 'Browsers',
    'page callback' => 'browscap_top_useragents',
    'page arguments' => array('browsers'),
    'access arguments' => array('view browscap reports'),
    'file' => 'browscap.reports.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  $items['admin/reports/browscap/crawlers'] = array(
    'title' => 'Crawlers',
    'page callback' => 'browscap_top_useragents',
    'page arguments' => array('crawlers'),
    'access arguments' => array('view browscap reports'),
    'file' => 'browscap.reports.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );
  $items['admin/reports/browscap/useragent/%browscap_useragent'] = array(
    'title' => 'Useragent details',
    'page callback' => 'browscap_useragent_properties',
    'page arguments' => array(4),
    'access arguments' => array('view browscap reports'),
    'file' => 'browscap.user_agent.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );
  return $items;
}

/**
 * Implementation of hook_exit().
 *
 * Keep tabs on browsers that visit
 */
function browscap_exit() {
  // If monitoring is enabled, record the browser
  if (variable_get('browscap_monitor', FALSE)) {
    if ($browser = browscap_get_browser()) {
      $browserstring = substr(trim($browser['parent']), 0, 255);
      if ($browserstring == '' or $browserstring == 'Default Browser') {
        $browserstring = substr(trim($_SERVER['HTTP_USER_AGENT']), 0, 255);
      }
      db_query("UPDATE {browscap_statistics} SET counter = counter + 1, is_crawler=%d ".
        "WHERE parent='%s'", $browser['crawler'], $browserstring);
      // If we affected 0 rows, this is the first time we've seen this browser
      if (!db_affected_rows()) {
        // We must create a new row to store counters for the new browser.
        db_query('INSERT INTO {browscap_statistics} (parent,counter,is_crawler) '.
          "VALUES('%s', 1, %d)", $browserstring, $browser['crawler']);
      }
    }
  }
}

/**
 * Implementation of hook_cron().
 */
function browscap_cron() {
  // How often should a check for updates occur (in days)?
  $update_interval = variable_get('browscap_update_interval', 7);

  // Convert the update interval from days to seconds
  $update_interval = $update_interval * 7 * 24 * 60 * 60;

  // Find out when the last update occurred
  $last_imported = variable_get('browscap_imported', REQUEST_TIME);

  // Has it been long enough since the last update was attempted?
  if (($last_imported + $update_interval) < REQUEST_TIME) {
    _browscap_import();
    variable_set('browscap_imported', time());
  }
}

/**
 * Provide data about the current browser or a known user agent string.
 *
 * @param string $useragent
 *   Optional user agent string to test.  If empty use the value from the current request.
 * @return array
 *  An array of data about the user agent.
 */
function browscap_get_browser($useragent = NULL) {
  if (!$useragent && isset($_SERVER['HTTP_USER_AGENT'])) {
    $useragent = $_SERVER['HTTP_USER_AGENT'];
  }
  // Cache the results
  $cacheid = $useragent;
  $cache = cache_get($cacheid, 'cache_browscap');
  if ((!empty($cache)) and ($cache->created > time() - 60*60*24)) {
    // Found a fresh entry in the cache
    $browserinfo = $cache->data;
  }
  else {
    // Note the 'backwards' use of LIKE - the useragent column contains
    // the wildcarded pattern to match against our full-length string
    // The ORDER BY chooses the most-specific matching pattern
    $browserinfo = db_fetch_object(db_query_range(
      "SELECT * from {browscap} WHERE '%s' LIKE useragent ORDER BY LENGTH(useragent) DESC",
      $useragent, 0, 1));
    // A couple of fieldnames not in our database, provided for
    // compatibility with PHP's get_browser()
    //$browserinfo->tables = $browserinfo->htmltables;
    cache_set($cacheid, $browserinfo, 'cache_browscap');
  }
  if (isset($browserinfo) && isset($browserinfo->data)) {
    $info = unserialize($browserinfo->data);
    $info['useragent'] = $useragent;
    $info['browser_name_pattern'] = strtr($browserinfo->useragent, '%_', '*?');
    return $info;
  }
}

/**
 * Determine whether the current visitor
 *
 * @param string $useragent
 *   Optional user agent string.
 */
function browscap_is_crawler($useragent = NULL) {
  $browser = browscap_get_browser($useragent);
  return (bool)$browser['crawler'];
}

/**
 * Loads details about a given useragent. Also used as a menu object loader.
 *
 * @param $useragent
 *   The name of the useragent to load.
 * @return
 *   The useragent array, FALSE otherwise.
 */
function browscap_useragent_load($useragent = NULL) {
  if (empty($useragent)) {
    return FALSE;
  }
  $row = db_fetch_object(db_query("SELECT * FROM {browscap} WHERE useragent = '%s'", $useragent));
  if (!$row) {
    return FALSE;
  }
  return unserialize($row->data);
}
